### ISSUE TITLE
Referencing final variables in anonymous classes

### ISSUE THREAD

**Issue by nguyenhoan** [stg-tud/MUDetect#10]
http://mubench.svamann.de/fse18-ext/private/experiments/2/detectors/MuDetect_180301_1_LabelVisitor/projects/testng/versions/677302c/misuses/finding-14/reviewers/hoan?origin=/fse18-ext/private/experiments/2/detectors/MuDetect_180301_1_LabelVisitor/runs&ex2_review_size=20

**Comment by salsolatragus** [comment]
What do you have in mind here? The violation is actually correct. The pattern comes from the methods that take a message as a third parameter, and this message is passed to both the constructor and the call in the anonymous inner class. Whereas in the violation we have the delta as third parameter, which is only used in the anonymous class. Admittedly, this is difficult to grasp from the output, because we match all data nodes, such that the String node in the pattern becomes an int node in the display...

**Comment by nguyenhoan** [comment]
Ok. I got it now. I thought AUG building could not figure out one of the final parameter was used in the call inside anonymous class.
But you we are right. Both parameters of that call are there.
